// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgreskT-N5DipmUk-zoUaSEmgLoGCzRw',
    appId: '1:669523429077:web:7e3961f2f54dea9175445c',
    messagingSenderId: '669523429077',
    projectId: 'iithar-project',
    authDomain: 'iithar-project.firebaseapp.com',
    storageBucket: 'iithar-project.appspot.com',
    measurementId: 'G-BZRF2PC10C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKB_hgfIxv7rHN8lvDymRid5_V-AeC6Rw',
    appId: '1:669523429077:android:1dba989a8a71ae3775445c',
    messagingSenderId: '669523429077',
    projectId: 'iithar-project',
    storageBucket: 'iithar-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9HLio3G2GSkLSLRf-YjXS8mM9Jpxcx8',
    appId: '1:669523429077:ios:8638087eedff9ea175445c',
    messagingSenderId: '669523429077',
    projectId: 'iithar-project',
    storageBucket: 'iithar-project.appspot.com',
    iosBundleId: 'com.example.iithar',
  );
}
// Future<void>  handleBackgroundMessage (RemoteMessage message) async{
//   print('Title: ${message.notification?.title}');
//   print('Body: ${message.notification?.body}');
//   print('Playload: ${message.data}');
// }
// class FirebaseApi{
//   final _firebasrMessaging = FirebaseMessaging.instance;
//   Future<void> initNotifications () async {
//     await _firebasrMessaging.requestPermission();
//     final fcmToken = await _firebasrMessaging.getToken();
//     print('token: $fcmToken'); 
//     FirebaseMessaging.onBackgroundMessage(handleBackgroundMessage);
//   }
// }