name: iithar
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  smooth_page_indicator: ^1.0.1
  shared_preferences: ^2.2.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.0
  get: ^4.6.5
  intl: ^0.19.0
  flutter_map_marker_popup: ^7.0.0
  custom_info_window: ^1.0.1
  flutter_datetime_picker: ^1.5.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  android_intent_plus: ^5.1.0
  timezone: ^0.9.4
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^15.1.3
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Animation/icon99.json
    - assets\Images\girl.png
    - assets\Images\search.png
    - assets/Images/intro.png
    - assets/icons/icon10.png
    - assets/icons/icon8.png
    - assets/icons/icon6.png
    - assets/icons/icon3.png
    - assets/icons/icon1.png
    - assets/icons/icon2.png
    - assets/icons/icons8-notification-64.png
    - assets/Images/Ve.png
    - assets/Images/bg.png
    - assets/icons/logo.png
    - assets/icons/datetime.png

  fonts:
    - family: HSI
      fonts:
        - asset: assets/fonts/HSI.ttf
    - family: BAHIJ
      fonts:
        - asset: assets/fonts/Bahij.ttf
